### ISSUE TITLE
1.1.0 TODO

### ISSUE THREAD

**Issue by found-cake** [found-cake/sch_sw_notice#1]
- [ ] SW 공지 toggle
- [x] 새로운 공지 출력시 뒤에 NEW 제거
- [ ] 색상 커스텀
- [x] 채널 삭제 시 guild id가 아닌 channel id로
- [x] 로그
- [x] 비동기 버그 가능성 해결(#2 )
- [ ] scope manager
